services:
  - type: web
    runtime: python
    name: theos-compiler-bot
    region: frankfurt
    plan: free
    buildCommand: "bash install.sh"
    startCommand: "python3 bot.py"
    healthCheckPath: /health
    envVars:
      - key: TELEGRAM_TOKEN
        value: "8683956903:AAHfM4eybz3oLKi-SWXr6TzsHzMRaoUwI-M"
      - key: LOG_GROUP_ID
        value: "0"
      - key: THEOS
        value: "/opt/render/project/src/theos"
      - key: MAX_CONCURRENT_BUILDS
        value: "1"
      - key: BUILD_TIMEOUT
        value: "900"
      - key: MAX_FILE_SIZE_MB
        value: "100"
      - key: RATE_LIMIT_MINUTES
        value: "1"
